src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Chaque Bien doit avoir un titre unique, celui-ci est déjà utilisé"
 * )
 */
class Property
{
    const HEAT=[
        '0' => 'électric',
        '1' => 'gaz'
    ];
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 10,
     *      max = 30,
     *      minMessage = "Le titre d'un bien doit avoir au moins {{ limit }} caractères",
     *      maxMessage = "Le titre d'un bien doit avoir au plus {{ limit }} caractères",
     *      allowEmptyString = false
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     *  @Assert\Range(
     *      min = 60,
     *      max = 250,
     *      notInRangeMessage = "La surface habittable proposé est entre {{ min }}m² et {{ max }}m²",
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 3,
     *      max = 6,
     *      notInRangeMessage = "On propose que nos Biens ne doit avoir qu'au moins {{ min }} pièces et au plus {{ max }} pièces",
     * )
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     *  @Assert\Range(
     *      min = 2,
     *      max = 5,
     *      notInRangeMessage = "On propose que nos Biens ne doit avoir qu'au moins {{ min }} chambres et au plus {{ max }} chambres",
     * )
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 50000000,
     *      max = 1000000000,
     *      notInRangeMessage = "On propose que nos Biens ne doit couter moins de 50 M Ar et ne dépasse pas 1 milliard Ar",
     * )
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *      pattern="/^[0-9]{3}/",
     *      message="Un code postal est composé de 3 chiffres",
     * )
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct(){
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, "", ",").' Ar';
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
//use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
            ->add('surface', NumberType::class)
            ->add('rooms', NumberType::class)
            ->add('bedrooms', NumberType::class)
            ->add('floor', NumberType::class)
            ->add('price', NumberType::class)
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getHeatChoices()
            ])
            ->add('city', TextType::class)
            ->add('address', TextType::class)
            ->add('postal_code', TextType::class)
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getHeatChoices(){
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $p){
            $output[$p] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repo, ManagerRegistry $manager){
        $this->repository = $repo;
        $this->em = $manager->getManager();
    }

    /**
     * @Route("/property", name="property.index")
     */
    public function index(): Response
    {

        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
            'properties' => $properties
        ]);
    }

    /**
     * @Route("/biens/{slug}.{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show(Property $property, string $slug): Response
    {
        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show',[
                'id'=>$property->getId(),
                'slug'=>$property->getSlug()
            ]);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'propereties'
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Properties{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Projects/symfony4_2nd/src/Controller/PropertyController.php'|file_link(0) }}">src/Controller/PropertyController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Projects/symfony4_2nd/templates/property/index.html.twig'|file_link(0) }}">templates/property/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-8">

            </div>
            <div class="col-md-4">
                <h1 class="text-info" style="text-transform: capitalize;">
                    {{ property.title }}
                </h1>
                <h3>{{ property.rooms }} pièces - {{ property.surface }} m²</h3>
                <div class="text-info" style="font-size: 3rem; font-weight:bold ;">{{ property.formatedPrice }}</div>
                <a href="#" class="btn btn-primary">Contecter l'agence</a>
            </div>
        </div>
        <p>{{ property.description | nl2br }}</p>

        <div class="row">
            <div class="col-md-8">
                <h2 class="text-warning" >Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Nombre de Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td style="text-transform: capitalize;">{{ property.heatType }}</td>
                    </tr>
                    <tr>
                        <td style="text-transform: capitalize;">étage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2 class="text-warning">Spécificités</h2>
            </div>
        </div>
    </div>
    

{% endblock %}